### ISSUE TITLE
IDE: greps for exampleTempProject when running SuperCollider projects ...

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/Bela#183]
... but should grep for scsynth/sclang instead (depending on what it does. What does it do?)

errors in the IDE log:
```
{ Error: Command failed: pgrep exampleTempProj

    at ChildProcess.exithandler (child_process.js:202:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:850:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'pgrep exampleTempProj' }
{ Error: Command failed: pgrep exampleTempProj

    at ChildProcess.exithandler (child_process.js:202:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:492:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'pgrep exampleTempProj' }
{ Error: Command failed: pgrep exampleTempProj

    at ChildProcess.exithandler (child_process.js:202:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:850:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'pgrep exampleTempProj' }

```

**Comment by LBDonovan** [comment]
This is about finding the linux process CPU usage. Is the process not given the name of the project when you run SuperCollider?

**Comment by giuliomoro** [comment]
no it is run as sclang. But the CPU metric  displayed by the IDE is reasonable, despite these errors

**Comment by giuliomoro** [comment]
No, the running process is called sclang. 
Still, the CpU usage displays a reasonable value when the process is running
