### ISSUE TITLE
Ensure IDE runs transparently on 3.8 and 4.4

### ISSUE THREAD

**Issue by LBDonovan** [BelaPlatform/Bela#332]

**Comment by giuliomoro** [comment]
Broken: if a file exists in `/opt/Bela/startup_env` that indicates running on boot is enabled, then you get 
```
starting IDE
setting pwd timeout
listening on port 80
setting pwd timeout
project dest set to run on boot
uncaughtException
/root/Bela/IDE/libs/IDE-node.js:535
	throw err;
	^

Error: spawn journalctl ENOENT
    at exports._errnoException (util.js:949:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by giuliomoro** [comment]
broken: CPU usage (and maybe mode switch detector?) not showing on 3.8

But I get these in the dev console:

```
bela
:
"CPU  PID    MSW        CSW        PF    STAT       %CPU  NAME↵  0  0      0          4689659    0     00500080   86.3  ROOT↵  0  3740   1          1          0     00b00380    0.0  minimal↵  0  3744   1          1460121    0     00300184   10.9  bela-audio↵  0  0      0          4801780    0     00000000    2.1  IRQ67: [timer]↵"
belaLinux:0
```
