### ISSUE TITLE
IDE: if board_detect fails, it does not load properly (and date does not get set)

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/Bela#452]
handle this more gracefully, use a default value and keep with setting the date.

**Comment by giuliomoro** [comment]
@LBDonovan 

The other problem is here https://github.com/BelaPlatform/Bela/blob/master/IDE/dist/main.js#L167-L174

If there is anything going out of the standard error, currently the promise is rejected. There is no reason why that should be the case. Standard error does not mean trouble. A non-0 return value means trouble.

**Comment by giuliomoro** [comment]
although, whatever trouble happens with `board_detect`, this should NOT prevent the IDE from loading. Ever.

**Comment by giuliomoro** [comment]
```
Mar 23 02:19:16 bela node[238]: running on CtagBeast
Mar 23 02:19:16 bela node[238]: (node:238) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): Failed to write register 1 on I2c codec
Mar 23 02:19:16 bela node[238]: Failed to reset I2C codec
Mar 23 02:19:16 bela node[238]: UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): Failed to write register 1 on I2c codec
Mar 23 02:19:16 bela node[238]: Failed to reset I2C codec
Mar 23 02:19:16 bela node[238]:     at emitWarning (internal/process/promises.js:59:21)
Mar 23 02:19:16 bela node[238]:     at emitPendingUnhandledRejections (internal/process/promises.js:86:11)
Mar 23 02:19:16 bela node[238]:     at process._tickCallback (internal/process/next_tick.js:110:7)
Mar 23 02:19:21 bela node[238]: error refreshing file list Error: ENOENT: no such file or directory, scandir '/root/Bela/projects/null'
```

**Comment by giuliomoro** [comment]
this still has problems even after the fix above is in place.

**Comment by giuliomoro** [comment]
As denoted by https://github.com/BelaPlatform/Bela/issues/504, if something fails when handling the return value of `board_detect` (for a reason different than the one fixed above), this prevents the date from being set. This makes not sense and should be rectified.
