### ISSUE TITLE
IDE: after MaxListenersExceededWarning, no projects are listed and IDE has to be restarted

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/Bela#469]
```
Jun 03 13:53:56 bela systemd[1]: Started Bela IDE Launcher.
Jun 03 13:54:11 bela node[249]: starting IDE
Jun 03 13:54:11 bela node[249]: setting pwd timeout
Jun 03 13:54:11 bela node[249]: listening on port 80
Jun 03 13:54:19 bela node[249]: setting pwd timeout
Jun 03 13:54:31 bela node[249]: (node:249) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 101 release listeners added. Use emitter.setMaxListeners() to inc
Jun 03 13:54:31 bela node[249]: MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 101 release listeners added. Use emitter.setMaxListeners() to increase limit
Jun 03 13:54:31 bela node[249]:     at _addListener (events.js:262:19)
Jun 03 13:54:31 bela node[249]:     at EventEmitter.addListener (events.js:279:10)
Jun 03 13:54:31 bela node[249]:     at /root/Bela/IDE/dist/Lock.js:29:22
Jun 03 13:54:31 bela node[249]:     at Lock.acquire (/root/Bela/IDE/dist/Lock.js:13:16)
Jun 03 13:54:31 bela node[249]:     at /root/Bela/IDE/dist/FileManager.js:171:51
Jun 03 13:54:31 bela node[249]:     at step (/root/Bela/IDE/dist/FileManager.js:32:23)
Jun 03 13:54:31 bela node[249]:     at Object.next (/root/Bela/IDE/dist/FileManager.js:13:53)
Jun 03 13:54:31 bela node[249]:     at /root/Bela/IDE/dist/FileManager.js:7:71
Jun 03 13:54:31 bela node[249]:     at __awaiter (/root/Bela/IDE/dist/FileManager.js:3:12)
Jun 03 13:54:31 bela node[249]:     at read_directory (/root/Bela/IDE/dist/FileManager.js:167:12)
Jun 03 13:54:31 bela node[249]:     at Object.<anonymous> (/root/Bela/IDE/dist/FileManager.js:296:46)
Jun 03 13:54:31 bela node[249]:     at step (/root/Bela/IDE/dist/FileManager.js:32:23)
Jun 03 13:54:31 bela node[249]:     at Object.next (/root/Bela/IDE/dist/FileManager.js:13:53)
Jun 03 13:54:31 bela node[249]:     at /root/Bela/IDE/dist/FileManager.js:7:71
Jun 03 13:54:31 bela node[249]:     at __awaiter (/root/Bela/IDE/dist/FileManager.js:3:12)
Jun 03 13:54:31 bela node[249]:     at Object.deep_read_directory (/root/Bela/IDE/dist/FileManager.js:292:12)
Jun 03 13:54:33 bela node[249]: setting pwd timeout
Jun 03 13:54:35 bela node[249]: running on Bela
Jun 03 13:55:01 bela node[249]: setting pwd timeout
Jun 03 14:02:22 bela node[249]: error refreshing file list Error: ENOENT: no such file or directory, scandir '/root/Bela/projects/null'
Jun 03 14:08:04 bela node[249]: setting pwd timeout
```

Loading the IDE page, no projects are listed, previously open file is not opened. Tried multiple refresh. No luck.
`~/Bela/IDE/settings.json` looks like this:
`{"project":"gen","liveAutocompletion":1,"liveSyntaxChecking":0,"verboseErrors":0,"cpuMonitoring":1,"cpuMonitoringVerbose":0,"consoleDelete":0,"viewHiddenFiles":0}`
and the project `~/Bela/projects/gen` does exist.

So I restart the service 
```
systemctl restart bela_ide
```
and this gives the following additional log
```
Jun 03 14:09:53 bela systemd[1]: Stopping Bela IDE Launcher...
Jun 03 14:09:53 bela systemd[1]: Stopped Bela IDE Launcher.
Jun 03 14:09:53 bela systemd[1]: Started Bela IDE Launcher.
Jun 03 14:10:04 bela node[12450]: starting IDE
Jun 03 14:10:05 bela node[12450]: setting pwd timeout
Jun 03 14:10:05 bela node[12450]: listening on port 80
Jun 03 14:10:09 bela node[12450]: setting pwd timeout
Jun 03 14:10:10 bela node[12450]: error refreshing file list Error: ENOENT: no such file or directory, scandir '/root/Bela/projects/null'
Jun 03 14:10:10 bela node[12450]: error refreshing file list Error: ENOENT: no such file or directory, scandir '/root/Bela/projects/null'
Jun 03 14:10:10 bela node[12450]: running on Bela
Jun 03 14:10:10 bela node[12450]: error refreshing file list Error: ENOENT: no such file or directory, scandir '/root/Bela/projects/null'
Jun 03 14:10:10 bela node[12450]: error refreshing file list Error: ENOENT: no such file or directory, scandir '/root/Bela/projects/null'
Jul 01 17:13:37 bela node[12450]: time set to: Sun Jul  1 17:13:37 UTC 2018
```
and the IDE finally works.

**Comment by roberthjack** [comment]
```
root@bela:~# journalctl -u bela_ide | cat
-- Logs begin at Thu 2016-11-03 17:16:43 UTC, end at Wed 2019-03-06 17:09:24 UTC. --
Nov 03 17:16:49 bela systemd[1]: Started Bela IDE Launcher.
Nov 03 17:17:01 bela node[244]: starting IDE
Nov 03 17:17:02 bela node[244]: setting pwd timeout
Nov 03 17:17:02 bela node[244]: listening on port 80
Nov 03 17:17:07 bela node[244]: setting pwd timeout
Nov 03 17:17:07 bela node[244]: setting pwd timeout
Nov 03 17:17:09 bela node[244]: (node:244) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 101 release listeners added. Use emitter.setMaxListeners() to increase limit
Nov 03 17:17:09 bela node[244]: MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 101 release listeners added. Use emitter.setMaxListeners() to increase limit
Nov 03 17:17:09 bela node[244]:     at _addListener (events.js:280:19)
Nov 03 17:17:09 bela node[244]:     at EventEmitter.addListener (events.js:297:10)
Nov 03 17:17:09 bela node[244]:     at /root/Bela/IDE/dist/Lock.js:29:22
Nov 03 17:17:09 bela node[244]:     at new Promise (<anonymous>)
Nov 03 17:17:09 bela node[244]:     at Lock.acquire (/root/Bela/IDE/dist/Lock.js:13:16)
Nov 03 17:17:09 bela node[244]:     at /root/Bela/IDE/dist/FileManager.js:171:51
Nov 03 17:17:09 bela node[244]:     at step (/root/Bela/IDE/dist/FileManager.js:32:23)
Nov 03 17:17:09 bela node[244]:     at Object.next (/root/Bela/IDE/dist/FileManager.js:13:53)
Nov 03 17:17:09 bela node[244]:     at /root/Bela/IDE/dist/FileManager.js:7:71
Nov 03 17:17:09 bela node[244]:     at new Promise (<anonymous>)
Nov 03 17:17:09 bela node[244]:     at __awaiter (/root/Bela/IDE/dist/FileManager.js:3:12)
Nov 03 17:17:09 bela node[244]:     at read_directory (/root/Bela/IDE/dist/FileManager.js:167:12)
Nov 03 17:17:09 bela node[244]:     at Object.<anonymous> (/root/Bela/IDE/dist/FileManager.js:296:46)
Nov 03 17:17:09 bela node[244]:     at step (/root/Bela/IDE/dist/FileManager.js:32:23)
Nov 03 17:17:09 bela node[244]:     at Object.next (/root/Bela/IDE/dist/FileManager.js:13:53)
Nov 03 17:17:09 bela node[244]:     at /root/Bela/IDE/dist/FileManager.js:7:71
Nov 03 17:17:13 bela node[244]: running on Bela
Nov 03 17:17:13 bela node[244]: running on Bela
Mar 06 17:06:23 bela node[244]: time set to: Wed Mar  6 17:06:23 UTC 2019
Mar 06 17:06:23 bela node[244]: time set to: Wed Mar  6 17:06:23 UTC 2019
Mar 06 17:08:15 bela node[244]: setting pwd timeout
Mar 06 17:08:28 bela node[244]: setting pwd timeout
Mar 06 17:08:28 bela node[244]: running on Bela
Mar 06 17:08:30 bela node[244]: time set to: Wed Mar  6 17:08:30 UTC 2019
```

**Comment by giuliomoro** [comment]
```
-- Logs begin at Thu 2016-11-03 17:16:43 UTC, end at Mon 2019-03-11 11:39:38 UTC. --
Nov 03 17:16:49 bela systemd[1]: Started Bela IDE Launcher.
Nov 03 17:17:02 bela node[233]: starting IDE
Nov 03 17:17:02 bela node[233]: setting pwd timeout
Nov 03 17:17:02 bela node[233]: listening on port 80
Nov 03 17:17:08 bela node[233]: setting pwd timeout
Nov 03 17:17:10 bela node[233]: (node:233) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 101 release listeners added. Use emitter.setMaxListeners() to increase limit
Nov 03 17:17:10 bela node[233]: MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 101 release listeners added. Use emitter.setMaxListeners() to increase limit
Nov 03 17:17:10 bela node[233]:     at _addListener (events.js:280:19)
Nov 03 17:17:10 bela node[233]:     at EventEmitter.addListener (events.js:297:10)
Nov 03 17:17:10 bela node[233]:     at /root/Bela/IDE/dist/Lock.js:29:22
Nov 03 17:17:10 bela node[233]:     at new Promise (<anonymous>)
Nov 03 17:17:10 bela node[233]:     at Lock.acquire (/root/Bela/IDE/dist/Lock.js:13:16)
Nov 03 17:17:10 bela node[233]:     at /root/Bela/IDE/dist/FileManager.js:171:51
Nov 03 17:17:10 bela node[233]:     at step (/root/Bela/IDE/dist/FileManager.js:32:23)
Nov 03 17:17:10 bela node[233]:     at Object.next (/root/Bela/IDE/dist/FileManager.js:13:53)
Nov 03 17:17:10 bela node[233]:     at /root/Bela/IDE/dist/FileManager.js:7:71
Nov 03 17:17:10 bela node[233]:     at new Promise (<anonymous>)
Nov 03 17:17:10 bela node[233]:     at __awaiter (/root/Bela/IDE/dist/FileManager.js:3:12)
Nov 03 17:17:10 bela node[233]:     at read_directory (/root/Bela/IDE/dist/FileManager.js:167:12)
Nov 03 17:17:10 bela node[233]:     at Object.<anonymous> (/root/Bela/IDE/dist/FileManager.js:296:46)
Nov 03 17:17:10 bela node[233]:     at step (/root/Bela/IDE/dist/FileManager.js:32:23)
Nov 03 17:17:10 bela node[233]:     at Object.next (/root/Bela/IDE/dist/FileManager.js:13:53)
Nov 03 17:17:10 bela node[233]:     at /root/Bela/IDE/dist/FileManager.js:7:71
Nov 03 17:17:11 bela node[233]: setting pwd timeout
Nov 03 17:17:15 bela node[233]: running on Bela
Mar 11 11:38:55 bela node[233]: time set to: Mon Mar 11 11:38:55 UTC 2019
Mar 11 11:39:08 bela node[233]: setting pwd timeout
Mar 11 11:39:38 bela node[233]: error refreshing file list Error: ENOENT: no such file or directory, scandir '/root/Bela/projects/null'
```

**Comment by giuliomoro** [comment]
also look at https://github.com/BelaPlatform/Bela/issues/517

**Comment by apmcpherson** [comment]
Confirmed that this still happens in the new IDE. Seems to be triggered by having a browser tab open from a previous session (in this case left open in Chrome since 2 days ago).

**Comment by giuliomoro** [comment]
@apmcpherson were you getting also the 

```
Mar 11 11:39:38 bela node[233]: error refreshing file list Error: ENOENT: no such file or directory, scandir '/root/Bela/projects/null'
```
line?

Because that part should have been fixed in https://github.com/BelaPlatform/Bela/commit/d382ac396541390a9e3123c5785e41e7d18ac300

To check if you have that specific commit on the board, the easiest way is to see if you have the  `projectExists()` function at the bottom of `IDE/src/ProjectManager.ts`.

**Comment by giuliomoro** [comment]
had a tab open with the IDE when I booted the board. Silly me !  (this is on `dev` btw, not on the branch that tries to fix this)

```
root@bela:~/Bela# journalctl -u bela_ide | cat
-- Logs begin at Thu 2016-11-03 17:16:43 UTC, end at Sat 2020-10-31 20:51:32 UTC. --
Oct 30 23:54:43 bela systemd[1]: Started Bela IDE Launcher.
Oct 30 23:54:52 bela node[547]: starting IDE from /root/Bela/
Oct 30 23:54:53 bela node[547]: setting pwd timeout
Oct 30 23:54:53 bela node[547]: listening on port 80
Oct 30 23:54:58 bela node[547]: setting pwd timeout
Oct 31 20:49:41 bela node[547]: setting pwd timeout
Oct 31 20:49:48 bela node[547]: (node:547) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 101 release listeners added. Use emitter.setMaxListeners() to increase limit
Oct 31 20:49:48 bela node[547]: MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 101 release listeners added. Use emitter.setMaxListeners() to increase limit
Oct 31 20:49:48 bela node[547]:     at _addListener (events.js:280:19)
Oct 31 20:49:48 bela node[547]:     at EventEmitter.addListener (events.js:297:10)
Oct 31 20:49:48 bela node[547]:     at /root/Bela/IDE/dist/Lock.js:29:22
Oct 31 20:49:48 bela node[547]:     at new Promise (<anonymous>)
Oct 31 20:49:48 bela node[547]:     at Lock.acquire (/root/Bela/IDE/dist/Lock.js:13:16)
Oct 31 20:49:48 bela node[547]:     at /root/Bela/IDE/dist/FileManager.js:279:51
Oct 31 20:49:48 bela node[547]:     at step (/root/Bela/IDE/dist/FileManager.js:32:23)
Oct 31 20:49:48 bela node[547]:     at Object.next (/root/Bela/IDE/dist/FileManager.js:13:53)
Oct 31 20:49:48 bela node[547]:     at /root/Bela/IDE/dist/FileManager.js:7:71
Oct 31 20:49:48 bela node[547]:     at new Promise (<anonymous>)
Oct 31 20:49:48 bela node[547]:     at __awaiter (/root/Bela/IDE/dist/FileManager.js:3:12)
Oct 31 20:49:48 bela node[547]:     at stat_file (/root/Bela/IDE/dist/FileManager.js:275:12)
Oct 31 20:49:48 bela node[547]:     at Object.<anonymous> (/root/Bela/IDE/dist/FileManager.js:498:46)
Oct 31 20:49:48 bela node[547]:     at step (/root/Bela/IDE/dist/FileManager.js:32:23)
Oct 31 20:49:48 bela node[547]:     at Object.next (/root/Bela/IDE/dist/FileManager.js:13:53)
Oct 31 20:49:48 bela node[547]:     at /root/Bela/IDE/dist/FileManager.js:7:71
Oct 31 20:49:48 bela node[547]: /root/Bela
Oct 31 20:49:53 bela node[547]: running on Bela
Oct 31 20:49:53 bela node[547]: time set to: Sat Oct 31 20:49:53 UTC 2020
Oct 31 20:49:53 bela node[547]: str: ./sc test: sc searchDir: /root/Bela/.
Oct 31 20:49:54 bela node[547]: running on Bela
Oct 31 20:49:55 bela node[547]: time set to: Sat Oct 31 20:49:54 UTC 2020
Oct 31 20:50:01 bela node[547]: setting pwd timeout
Oct 31 20:50:10 bela node[547]: setting pwd timeout
Oct 31 20:50:12 bela node[547]: str: ./sc test: sc searchDir: /root/Bela/.
Oct 31 20:50:12 bela node[547]: str: ./scmake test: scmake searchDir: /root/Bela/.
Oct 31 20:50:54 bela node[547]: setting pwd timeout
Oct 31 20:50:55 bela node[547]: running on Bela
Oct 31 20:50:55 bela node[547]: time set to: Sat Oct 31 20:50:55 UTC 2020
Oct 31 20:51:07 bela node[547]: running on Bela
Oct 31 20:51:09 bela node[547]: (node:547) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'pid' of undefined
Oct 31 20:51:09 bela node[547]:     at MakeProcess.stop (/root/Bela/IDE/dist/MakeProcess.js:117:54)
Oct 31 20:51:09 bela node[547]:     at Object.checkSyntax (/root/Bela/IDE/dist/ProcessManager.js:85:26)
Oct 31 20:51:09 bela node[547]:     at /root/Bela/IDE/dist/SocketManager.js:240:69
Oct 31 20:51:09 bela node[547]:     at step (/root/Bela/IDE/dist/SocketManager.js:32:23)
Oct 31 20:51:09 bela node[547]:     at Object.next (/root/Bela/IDE/dist/SocketManager.js:13:53)
Oct 31 20:51:09 bela node[547]:     at /root/Bela/IDE/dist/SocketManager.js:7:71
Oct 31 20:51:09 bela node[547]:     at new Promise (<anonymous>)
Oct 31 20:51:09 bela node[547]:     at __awaiter (/root/Bela/IDE/dist/SocketManager.js:3:12)
Oct 31 20:51:09 bela node[547]:     at process_event (/root/Bela/IDE/dist/SocketManager.js:232:12)
Oct 31 20:51:09 bela node[547]:     at Socket.<anonymous> (/root/Bela/IDE/dist/SocketManager.js:71:57)
Oct 31 20:51:09 bela node[547]:     at emitOne (events.js:116:13)
Oct 31 20:51:09 bela node[547]:     at Socket.emit (events.js:211:7)
Oct 31 20:51:09 bela node[547]:     at /root/Bela/IDE/node_modules/socket.io/lib/socket.js:514:12
Oct 31 20:51:09 bela node[547]:     at _combinedTickCallback (internal/process/next_tick.js:132:7)
Oct 31 20:51:09 bela node[547]:     at process._tickCallback (internal/process/next_tick.js:181:9)
Oct 31 20:51:09 bela node[547]: UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'pid' of undefined
Oct 31 20:51:09 bela node[547]:     at MakeProcess.stop (/root/Bela/IDE/dist/MakeProcess.js:117:54)
Oct 31 20:51:09 bela node[547]:     at Object.checkSyntax (/root/Bela/IDE/dist/ProcessManager.js:85:26)
Oct 31 20:51:09 bela node[547]:     at /root/Bela/IDE/dist/SocketManager.js:240:69
Oct 31 20:51:09 bela node[547]:     at step (/root/Bela/IDE/dist/SocketManager.js:32:23)
Oct 31 20:51:09 bela node[547]:     at Object.next (/root/Bela/IDE/dist/SocketManager.js:13:53)
Oct 31 20:51:09 bela node[547]:     at /root/Bela/IDE/dist/SocketManager.js:7:71
Oct 31 20:51:09 bela node[547]:     at new Promise (<anonymous>)
Oct 31 20:51:09 bela node[547]:     at __awaiter (/root/Bela/IDE/dist/SocketManager.js:3:12)
Oct 31 20:51:09 bela node[547]:     at process_event (/root/Bela/IDE/dist/SocketManager.js:232:12)
Oct 31 20:51:09 bela node[547]:     at Socket.<anonymous> (/root/Bela/IDE/dist/SocketManager.js:71:57)
Oct 31 20:51:09 bela node[547]:     at emitOne (events.js:116:13)
Oct 31 20:51:09 bela node[547]:     at Socket.emit (events.js:211:7)
Oct 31 20:51:09 bela node[547]:     at /root/Bela/IDE/node_modules/socket.io/lib/socket.js:514:12
Oct 31 20:51:09 bela node[547]:     at _combinedTickCallback (internal/process/next_tick.js:132:7)
Oct 31 20:51:09 bela node[547]:     at process._tickCallback (internal/process/next_tick.js:181:9)
Oct 31 20:51:09 bela node[547]:     at emitWarning (internal/process/promises.js:65:17)
Oct 31 20:51:09 bela node[547]:     at emitPendingUnhandledRejections (internal/process/promises.js:109:11)
Oct 31 20:51:09 bela node[547]:     at runMicrotasksCallback (internal/process/next_tick.js:125:9)
Oct 31 20:51:09 bela node[547]:     at _combinedTickCallback (internal/process/next_tick.js:132:7)
Oct 31 20:51:09 bela node[547]:     at process._tickCallback (internal/process/next_tick.js:181:9)
Oct 31 20:51:09 bela node[547]: (node:547) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
Oct 31 20:51:09 bela node[547]: TypeError: Cannot read property 'pid' of undefined
Oct 31 20:51:09 bela node[547]:     at MakeProcess.stop (/root/Bela/IDE/dist/MakeProcess.js:117:54)
Oct 31 20:51:09 bela node[547]:     at Object.checkSyntax (/root/Bela/IDE/dist/ProcessManager.js:85:26)
Oct 31 20:51:09 bela node[547]:     at /root/Bela/IDE/dist/SocketManager.js:240:69
Oct 31 20:51:09 bela node[547]:     at step (/root/Bela/IDE/dist/SocketManager.js:32:23)
Oct 31 20:51:09 bela node[547]:     at Object.next (/root/Bela/IDE/dist/SocketManager.js:13:53)
Oct 31 20:51:09 bela node[547]:     at /root/Bela/IDE/dist/SocketManager.js:7:71
Oct 31 20:51:09 bela node[547]:     at new Promise (<anonymous>)
Oct 31 20:51:09 bela node[547]:     at __awaiter (/root/Bela/IDE/dist/SocketManager.js:3:12)
Oct 31 20:51:09 bela node[547]:     at process_event (/root/Bela/IDE/dist/SocketManager.js:232:12)
Oct 31 20:51:09 bela node[547]:     at Socket.<anonymous> (/root/Bela/IDE/dist/SocketManager.js:71:57)
Oct 31 20:51:09 bela node[547]:     at emitOne (events.js:116:13)
Oct 31 20:51:09 bela node[547]:     at Socket.emit (events.js:211:7)
Oct 31 20:51:09 bela node[547]:     at /root/Bela/IDE/node_modules/socket.io/lib/socket.js:514:12
Oct 31 20:51:09 bela node[547]:     at _combinedTickCallback (internal/process/next_tick.js:132:7)
Oct 31 20:51:09 bela node[547]:     at process._tickCallback (internal/process/next_tick.js:181:9)
Oct 31 20:51:09 bela node[547]: (node:547) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Oct 31 20:51:09 bela node[547]: DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Oct 31 20:51:09 bela node[547]:     at emitWarning (internal/process/promises.js:92:15)
Oct 31 20:51:09 bela node[547]:     at emitPendingUnhandledRejections (internal/process/promises.js:109:11)
Oct 31 20:51:09 bela node[547]:     at runMicrotasksCallback (internal/process/next_tick.js:125:9)
Oct 31 20:51:09 bela node[547]:     at _combinedTickCallback (internal/process/next_tick.js:132:7)
Oct 31 20:51:09 bela node[547]:     at process._tickCallback (internal/process/next_tick.js:181:9)
Oct 31 20:51:09 bela node[547]: make '--no-print-directory' '-C' '/root/Bela/' 'syntax' 'PROJECT=typing' 'CL=-p16 -C8 -B16 -H-6 -N1 -G1 -M0 -D0 -A0 --pga-gain-left=10 --pga-gain-right=10  -X0'
```

**Comment by apmcpherson** [comment]
I just had the same problem on the new branch: tabs left open when I booted, get no projects on the board. However the log is missing the `MaxListenersExceeded` warning:

```-- Logs begin at Thu 2016-11-03 17:16:43 UTC. --
Nov 03 17:16:53 bela systemd[1]: Started Bela IDE Launcher.
Nov 03 17:17:10 bela node[406]: starting IDE from /root/Bela/
Nov 03 17:17:11 bela node[406]: setting pwd timeout
Nov 03 17:17:11 bela node[406]: listening on port 80
Nov 03 17:17:11 bela node[406]: setting pwd timeout
Nov 03 17:17:11 bela node[406]: setting pwd timeout
Nov 03 17:17:12 bela node[406]: /root/Bela
Nov 03 17:17:48 bela node[406]: setting pwd timeout
Nov 03 17:17:57 bela node[406]: setting pwd timeout
```
So maybe something else is causing this?

**Comment by giuliomoro** [comment]
looks like it. (the lock is not logging anything because I made it log only if it's the `ProcessManager` lock), but clearly this is a separate issue. At least this is a bit more reproducible so there's hope.
