### ISSUE TITLE
IDE: delete a project (from the IDE) and you may cause "panic"

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/Bela#523]
```
root@bela:~/Bela/projects/shift-out# journalctl -u bela_ide  | cat
-- Logs begin at Thu 2018-12-13 16:09:12 UTC, end at Thu 2018-12-13 20:33:52 UTC. --
Dec 13 20:18:13 bela node[243]: setting pwd timeout
Dec 13 20:18:13 bela node[243]: running on Bela
Dec 13 20:18:14 bela node[243]: time set to: Thu Dec 13 20:18:14 UTC 2018
Dec 13 20:21:03 bela node[243]: bad process-event { event: 'rebuild', currentProject: 'shift' }
Dec 13 20:21:04 bela node[243]: make '--no-print-directory' '-C' '/root/Bela/' 'all' 'PROJECT=shift' 'CL=-p16 -C8 -B16 -H-6 -N1 -G1 -M0 -D0 -A0 --pga-gain-left=10 --pga-gain-right=10  -X0'
Dec 13 20:21:19 bela node[243]: make '--no-print-directory' '-C' '/root/Bela/' 'all' 'PROJECT=shift' 'CL=-p16 -C8 -B16 -H-6 -N1 -G1 -M0 -D0 -A0 --pga-gain-left=10 --pga-gain-right=10  -X0'
Dec 13 20:21:37 bela node[243]: make '--no-print-directory' '-C' '/root/Bela/' 'all' 'PROJECT=shift' 'CL=-p16 -C8 -B16 -H-6 -N1 -G1 -M0 -D0 -A0 --pga-gain-left=10 --pga-gain-right=10  -X0'
Dec 13 20:22:18 bela node[243]: make '--no-print-directory' '-C' '/root/Bela/' 'all' 'PROJECT=shift' 'CL=-p16 -C8 -B16 -H-6 -N1 -G1 -M0 -D0 -A0 --pga-gain-left=10 --pga-gain-right=10  -X0'
Dec 13 20:22:46 bela node[243]: project-event error:
Dec 13 20:22:46 bela node[243]: { Error: ENOTDIR: not a directory, scandir '/root/Bela/projects/.DS_Store'
Dec 13 20:22:46 bela node[243]:   cause:
Dec 13 20:22:46 bela node[243]:    { Error: ENOTDIR: not a directory, scandir '/root/Bela/projects/.DS_Store'
Dec 13 20:22:46 bela node[243]:      errno: -20,
Dec 13 20:22:46 bela node[243]:      code: 'ENOTDIR',
Dec 13 20:22:46 bela node[243]:      syscall: 'scandir',
Dec 13 20:22:46 bela node[243]:      path: '/root/Bela/projects/.DS_Store' },
Dec 13 20:22:46 bela node[243]:   isOperational: true,
Dec 13 20:22:46 bela node[243]:   errno: -20,
Dec 13 20:22:46 bela node[243]:   code: 'ENOTDIR',
Dec 13 20:22:46 bela node[243]:   syscall: 'scandir',
Dec 13 20:22:46 bela node[243]:   path: '/root/Bela/projects/.DS_Store' }
Dec 13 20:22:48 bela node[243]: error refreshing file list Error: ENOTDIR: not a directory, scandir '/root/Bela/projects/.DS_Store'
Dec 13 20:23:18 bela node[243]: error refreshing file list Error: ENOENT: no such file or directory, lstat '/root/Bela/projects/shift-out/ShiftOut.h'
Dec 13 20:23:42 bela node[243]: make '--no-print-directory' '-C' '/root/Bela/' 'all' 'PROJECT=shift-out' 'CL=-p16 -C8 -B16 -H-6 -N1 -G1 -M0 -D0 -A0 --pga-gain-left=10 --pga-gain-right=10  -X0'
Dec 13 20:24:17 bela node[243]: make '--no-print-directory' '-C' '/root/Bela/' 'all' 'PROJECT=shift-out' 'CL=-p16 -C8 -B16 -H-6 -N1 -G1 -M0 -D0 -A0 --pga-gain-left=10 --pga-gain-right=10  -X0'
Dec 13 20:24:57 bela node[243]: make '--no-print-directory' '-C' '/root/Bela/' 'all' 'PROJECT=shift-out' 'CL=-p16 -C8 -B16 -H-6 -N1 -G1 -M0 -D0 -A0 --pga-gain-left=10 --pga-gain-right=10  -X0'
Dec 13 20:25:02 bela node[243]: make '--no-print-directory' '-C' '/root/Bela/' 'all' 'PROJECT=shift-out' 'CL=-p16 -C8 -B16 -H-6 -N1 -G1 -M0 -D0 -A0 --pga-gain-left=10 --pga-gain-right=10  -X0'
Dec 13 20:25:33 bela node[243]: make '--no-print-directory' '-C' '/root/Bela/' 'all' 'PROJECT=shift-out' 'CL=-p16 -C8 -B16 -H-6 -N1 -G1 -M0 -D0 -A0 --pga-gain-left=10 --pga-gain-right=10  -X0'
Dec 13 20:26:30 bela node[243]: make '--no-print-directory' '-C' '/root/Bela/' 'all' 'PROJECT=shift-out' 'CL=-p16 -C8 -B16 -H-6 -N1 -G1 -M0 -D0 -A0 --pga-gain-left=10 --pga-gain-right=10  -X0'
Dec 13 20:27:04 bela node[243]: make '--no-print-directory' '-C' '/root/Bela/' 'all' 'PROJECT=shift-out' 'CL=-p16 -C8 -B16 -H-6 -N1 -G1 -M0 -D0 -A0 --pga-gain-left=10 --pga-gain-right=10  -X0'
Dec 13 20:28:09 bela node[243]: make '--no-print-directory' '-C' '/root/Bela/' 'all' 'PROJECT=shift-out' 'CL=-p16 -C8 -B16 -H-6 -N1 -G1 -M0 -D0 -A0 --pga-gain-left=10 --pga-gain-right=10  -X0' 'LDLIBS=-lpd'
Dec 13 20:28:11 bela node[243]: make '--no-print-directory' '-C' '/root/Bela/' 'runide' 'PROJECT=shift-out' 'CL=-p16 -C8 -B16 -H-6 -N1 -G1 -M0 -D0 -A0 --pga-gain-left=10 --pga-gain-right=10  -X0' 'LDLIBS=-lpd'
Dec 13 20:28:23 bela node[243]: bad process-event { event: 'rebuild', currentProject: 'shift-out' }
Dec 13 20:28:35 bela node[243]: make '--no-print-directory' '-C' '/root/Bela/' 'all' 'PROJECT=shift-out' 'CL=-p16 -C8 -B16 -H-6 -N1 -G1 -M0 -D0 -A0 --pga-gain-left=10 --pga-gain-right=10  -X0'
Dec 13 20:28:35 bela node[243]: make '--no-print-directory' '-C' '/root/Bela/' 'runide' 'PROJECT=shift-out' 'CL=-p16 -C8 -B16 -H-6 -N1 -G1 -M0 -D0 -A0 --pga-gain-left=10 --pga-gain-right=10  -X0'
Dec 13 20:28:39 bela node[243]: make '--no-print-directory' '-C' '/root/Bela/' 'all' 'PROJECT=shift-out' 'CL=-p16 -C8 -B16 -H-6 -N1 -G1 -M0 -D0 -A0 --pga-gain-left=10 --pga-gain-right=10  -X0'
Dec 13 20:28:45 bela node[243]: make '--no-print-directory' '-C' '/root/Bela/' 'runide' 'PROJECT=shift-out' 'CL=-p16 -C8 -B16 -H-6 -N1 -G1 -M0 -D0 -A0 --pga-gain-left=10 --pga-gain-right=10  -X0'
Dec 13 20:29:09 bela node[243]: make '--no-print-directory' '-C' '/root/Bela/' 'all' 'PROJECT=shift-out' 'CL=-p16 -C8 -B16 -H-6 -N1 -G1 -M0 -D0 -A0 --pga-gain-left=10 --pga-gain-right=10  -X0'
Dec 13 20:29:09 bela node[243]: make '--no-print-directory' '-C' '/root/Bela/' 'runide' 'PROJECT=shift-out' 'CL=-p16 -C8 -B16 -H-6 -N1 -G1 -M0 -D0 -A0 --pga-gain-left=10 --pga-gain-right=10  -X0'
Dec 13 20:29:10 bela node[243]: Failed to get CPU usage
Dec 13 20:30:01 bela node[243]: make '--no-print-directory' '-C' '/root/Bela/' 'all' 'PROJECT=shift-out' 'CL=-p16 -C8 -B16 -H-6 -N1 -G1 -M0 -D0 -A0 --pga-gain-left=10 --pga-gain-right=10  -X0'
Dec 13 20:30:06 bela node[243]: bad process-event { event: 'rebuild', currentProject: 'shift-out' }
Dec 13 20:30:07 bela node[243]: make '--no-print-directory' '-C' '/root/Bela/' 'all' 'PROJECT=shift-out' 'CL=-p16 -C8 -B16 -H-6 -N1 -G1 -M0 -D0 -A0 --pga-gain-left=10 --pga-gain-right=10  -X0'
Dec 13 20:30:14 bela node[243]: make '--no-print-directory' '-C' '/root/Bela/' 'runide' 'PROJECT=shift-out' 'CL=-p16 -C8 -B16 -H-6 -N1 -G1 -M0 -D0 -A0 --pga-gain-left=10 --pga-gain-right=10  -X0'
Dec 13 20:31:18 bela node[243]: make '--no-print-directory' '-C' '/root/Bela/' 'all' 'PROJECT=shift-out' 'CL=-p16 -C8 -B16 -H-6 -N1 -G1 -M0 -D0 -A0 --pga-gain-left=10 --pga-gain-right=10  -X0'
Dec 13 20:31:19 bela node[243]: Failed to get CPU usage
Dec 13 20:31:26 bela node[243]: make '--no-print-directory' '-C' '/root/Bela/' 'runide' 'PROJECT=shift-out' 'CL=-p16 -C8 -B16 -H-6 -N1 -G1 -M0 -D0 -A0 --pga-gain-left=10 --pga-gain-right=10  -X0'
Dec 13 20:31:33 bela node[243]: Failed to get CPU usage
Dec 13 20:31:40 bela node[243]: project-event error:
Dec 13 20:31:40 bela node[243]: { Error: ENOTDIR: not a directory, scandir '/root/Bela/projects/.DS_Store'
Dec 13 20:31:40 bela node[243]:   cause:
Dec 13 20:31:40 bela node[243]:    { Error: ENOTDIR: not a directory, scandir '/root/Bela/projects/.DS_Store'
Dec 13 20:31:40 bela node[243]:      errno: -20,
Dec 13 20:31:40 bela node[243]:      code: 'ENOTDIR',
Dec 13 20:31:40 bela node[243]:      syscall: 'scandir',
Dec 13 20:31:40 bela node[243]:      path: '/root/Bela/projects/.DS_Store' },
Dec 13 20:31:40 bela node[243]:   isOperational: true,
Dec 13 20:31:40 bela node[243]:   errno: -20,
Dec 13 20:31:40 bela node[243]:   code: 'ENOTDIR',
Dec 13 20:31:40 bela node[243]:   syscall: 'scandir',
Dec 13 20:31:40 bela node[243]:   path: '/root/Bela/projects/.DS_Store' }
Dec 13 20:31:43 bela node[243]: error refreshing file list Error: ENOTDIR: not a directory, scandir '/root/Bela/projects/.DS_Store'
Dec 13 20:31:48 bela node[243]: error refreshing file list Error: ENOTDIR: not a directory, scandir '/root/Bela/projects/.DS_Store'
Dec 13 20:31:53 bela node[243]: error refreshing file list Error: ENOTDIR: not a directory, scandir '/root/Bela/projects/.DS_Store'
Dec 13 20:31:58 bela node[243]: error refreshing file list Error: ENOTDIR: not a directory, scandir '/root/Bela/projects/.DS_Store'
Dec 13 20:32:03 bela node[243]: error refreshing file list Error: ENOTDIR: not a directory, scandir '/root/Bela/projects/.DS_Store'
Dec 13 20:32:08 bela node[243]: error refreshing file list Error: ENOTDIR: not a directory, scandir '/root/Bela/projects/.DS_Store'
Dec 13 20:32:13 bela node[243]: error refreshing file list Error: ENOTDIR: not a directory, scandir '/root/Bela/projects/.DS_Store'
Dec 13 20:32:14 bela node[243]: (node:243) UnhandledPromiseRejectionWarning: Error: ENOTDIR: not a directory, open '/root/Bela/projects/.DS_Store/settings.json'
Dec 13 20:32:14 bela node[243]: UnhandledPromiseRejectionWarning: Error: ENOTDIR: not a directory, open '/root/Bela/projects/.DS_Store/settings.json'
Dec 13 20:32:14 bela node[243]:     at emitWarning (internal/process/promises.js:65:17)
Dec 13 20:32:14 bela node[243]:     at emitPendingUnhandledRejections (internal/process/promises.js:109:11)
Dec 13 20:32:14 bela node[243]:     at runMicrotasksCallback (internal/process/next_tick.js:125:9)
Dec 13 20:32:14 bela node[243]:     at _combinedTickCallback (internal/process/next_tick.js:132:7)
Dec 13 20:32:14 bela node[243]:     at process._tickCallback (internal/process/next_tick.js:181:9)
Dec 13 20:32:14 bela node[243]: (node:243) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
Dec 13 20:32:14 bela node[243]: Error: ENOTDIR: not a directory, open '/root/Bela/projects/.DS_Store/settings.json'
Dec 13 20:32:14 bela node[243]: (node:243) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Dec 13 20:32:14 bela node[243]: DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Dec 13 20:32:14 bela node[243]:     at emitWarning (internal/process/promises.js:92:15)
Dec 13 20:32:14 bela node[243]:     at emitPendingUnhandledRejections (internal/process/promises.js:109:11)
Dec 13 20:32:14 bela node[243]:     at runMicrotasksCallback (internal/process/next_tick.js:125:9)
Dec 13 20:32:14 bela node[243]:     at _combinedTickCallback (internal/process/next_tick.js:132:7)
Dec 13 20:32:14 bela node[243]:     at process._tickCallback (internal/process/next_tick.js:181:9)
Dec 13 20:32:18 bela node[243]: error refreshing file list Error: ENOTDIR: not a directory, scandir '/root/Bela/projects/.DS_Store'
Dec 13 20:32:23 bela node[243]: error refreshing file list Error: ENOTDIR: not a directory, scandir '/root/Bela/projects/.DS_Store'
Dec 13 20:32:26 bela node[243]: setting pwd timeout
Dec 13 20:32:27 bela node[243]: running on Bela
Dec 13 20:32:27 bela node[243]: project-event error:
Dec 13 20:32:27 bela node[243]: { Error: ENOTDIR: not a directory, scandir '/root/Bela/projects/.DS_Store'
Dec 13 20:32:27 bela node[243]:   cause:
Dec 13 20:32:27 bela node[243]:    { Error: ENOTDIR: not a directory, scandir '/root/Bela/projects/.DS_Store'
Dec 13 20:32:27 bela node[243]:      errno: -20,
Dec 13 20:32:27 bela node[243]:      code: 'ENOTDIR',
Dec 13 20:32:27 bela node[243]:      syscall: 'scandir',
Dec 13 20:32:27 bela node[243]:      path: '/root/Bela/projects/.DS_Store' },
Dec 13 20:32:27 bela node[243]:   isOperational: true,
Dec 13 20:32:27 bela node[243]:   errno: -20,
Dec 13 20:32:27 bela node[243]:   code: 'ENOTDIR',
Dec 13 20:32:27 bela node[243]:   syscall: 'scandir',
Dec 13 20:32:27 bela node[243]:   path: '/root/Bela/projects/.DS_Store' }
Dec 13 20:32:27 bela node[243]: time set to: Thu Dec 13 20:32:27 UTC 2018
Dec 13 20:32:31 bela node[243]: error refreshing file list Error: ENOTDIR: not a directory, scandir '/root/Bela/projects/.DS_Store'
Dec 13 20:32:36 bela node[243]: error refreshing file list Error: ENOTDIR: not a directory, scandir '/root/Bela/projects/.DS_Store'
Dec 13 20:32:41 bela node[243]: error refreshing file list Error: ENOTDIR: not a directory, scandir '/root/Bela/projects/.DS_Store'
Dec 13 20:32:46 bela node[243]: error refreshing file list Error: ENOTDIR: not a directory, scandir '/root/Bela/projects/.DS_Store'
Dec 13 20:32:51 bela node[243]: error refreshing file list Error: ENOTDIR: not a directory, scandir '/root/Bela/projects/.DS_Store'
Dec 13 20:32:56 bela node[243]: error refreshing file list Error: ENOTDIR: not a directory, scandir '/root/Bela/projects/.DS_Store'
Dec 13 20:33:01 bela node[243]: error refreshing file list Error: ENOTDIR: not a directory, scandir '/root/Bela/projects/.DS_Store'
Dec 13 20:33:06 bela node[243]: error refreshing file list Error: ENOTDIR: not a directory, scandir '/root/Bela/projects/.DS_Store'
Dec 13 20:33:11 bela node[243]: error refreshing file list Error: ENOTDIR: not a directory, scandir '/root/Bela/projects/.DS_Store'
Dec 13 20:33:17 bela node[243]: error refreshing file list Error: ENOTDIR: not a directory, scandir '/root/Bela/projects/.DS_Store'
Dec 13 20:33:21 bela node[243]: error refreshing file list Error: ENOTDIR: not a directory, scandir '/root/Bela/projects/.DS_Store'
Dec 13 20:33:27 bela node[243]: error refreshing file list Error: ENOTDIR: not a directory, scandir '/root/Bela/projects/.DS_Store'
Dec 13 20:33:31 bela node[243]: error refreshing file list Error: ENOTDIR: not a directory, scandir '/root/Bela/projects/.DS_Store'
Dec 13 20:33:37 bela node[243]: error refreshing file list Error: ENOTDIR: not a directory, scandir '/root/Bela/projects/.DS_Store'
Dec 13 20:33:41 bela node[243]: error refreshing file list Error: ENOTDIR: not a directory, scandir '/root/Bela/projects/.DS_Store'
Dec 13 20:33:46 bela node[243]: error refreshing file list Error: ENOTDIR: not a directory, scandir '/root/Bela/projects/.DS_Store'
Dec 13 20:33:52 bela node[243]: error refreshing file list Error: ENOTDIR: not a directory, scandir '/root/Bela/projects/.DS_Store'
```

```
xenomai version: 3.0.7

bundle.js:633 running on Bela

/documentation_xml?file=OSCMessageFactory_8h:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
/documentation_xml?file=MidiParser_8h:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
bundle.js:4169 Uncaught TypeError: Cannot read property 'length' of null
    at FileView._fileList (bundle.js:2280)
    at FileView.modelChanged (bundle.js:4156)
    at Model.<anonymous> (bundle.js:4120)
    at Model.EventEmitter.emit (bundle.js:97)
    at Model.setKey (bundle.js:1075)
    at r.<anonymous> (bundle.js:682)
    at r.emit (index.js:83)
    at r.onevent (index.js:83)
    at r.onpacket (index.js:83)
    at r.<anonymous> (index.js:83)
```

**Comment by giuliomoro** [comment]
alternatively, say that you have a tab open with project xyz, then you plug in a different Bela that doesn't have project xyz: once the websocket reconnects, the IDE will desperately try to load project xyz and start panicking as above

**Comment by giuliomoro** [comment]
it no longer panics
