### ISSUE TITLE
Scope: somehow the frontend sent a message that crashed the backend

### ISSUE THREAD

**Issue by giuliomoro** [BelaPlatform/Bela#620]
`void Scope::scope_control_data(const char* data)`
received the following `data` (printed with `printf("data: %s\n", data)`:
```
{"numChannels":10,"sampleRate":44100,"numSliders":0,"frameWidth":1280,"plotMode":0,"triggerMode":0,"triggerChannel":0,"triggerDir":0,"triggerLevel":0,"xOffset":0,"upSampling":5,"downSampling":1,"FFTLength":1024,"FFTXAxis":0,"FFTYAxis":0,"holdOff":0,"interpolation":0,"xTimeBase":3,"frameHeight":721,"event":"connection-reply","\u0000ampleRate":44100,"\u0000umChannels":10}
```

```
#0  JSONValue::IsNumber (this=0x0) at core/JSONValue.cpp:538
#1  0x000376e0 in Scope::parse_settings (this=<optimized out>, value=<optimized out>) at libraries/Scope/Scope.cpp:587
#2  0x00037504 in Scope::scope_control_data (this=<optimized out>, data=<optimized out>) at libraries/Scope/Scope.cpp:574
#3  0x0003791c in Scope::setup(unsigned int, float)::$_0::operator()(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, void*, int) const (size=0,
    this=<optimized out>, address=..., buf=<optimized out>) at libraries/Scope/Scope.cpp:58
#4  std::_Function_handler<void (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, void*, int), Scope::setup(unsigned int, float)::$_0>::_M_invoke(std::_Any_data const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&, void*&&, int&&) (__functor=..., __args=<optimized out>,
    __args=<optimized out>, __args=<optimized out>) at /usr/bin/../lib/gcc/arm-linux-gnueabihf/6.3.0/../../../../include/c++/6.3.0/functional:1731
#5  0x00023508 in std::function<void (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, void*, int)>::operator()(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, void*, int) const (__args=<error reading variable: Cannot access memory at address 0x0>,
    __args=<error reading variable: Cannot access memory at address 0x0>, __args=<error reading variable: Cannot access memory at address 0x0>, this=<optimized out>)
    at /usr/bin/../lib/gcc/arm-linux-gnueabihf/6.3.0/../../../../include/c++/6.3.0/functional:2127
#6  WSServerDataHandler::onData (this=0x6b6f4, socket=<optimized out>,
    data=0xb6016508 "{\"numChannels\":10,\"sampleRate\":44100,\"numSliders\":0,\"frameWidth\":1280,\"plotMode\":0,\"triggerMode\":0,\"triggerChannel\":0,\"triggerDir\":0,\"triggerLevel\":0,\"xOffset\":0,\"upSampling\":5,\"downSampling\":1,\"FFTLe"...) at core/WSServer.cpp:31
#7  0xb6f68ade in seasocks::Connection::handleWebSocketTextMessage(char const*) () from /usr/local/lib/libseasocks.so.1.3.2
#8  0xb6f68762 in seasocks::Connection::handleHybiWebSocket() () from /usr/local/lib/libseasocks.so.1.3.2
#9  0xb6f66c9a in seasocks::Connection::handleNewData() () from /usr/local/lib/libseasocks.so.1.3.2
#10 0xb6f66972 in seasocks::Connection::handleDataReadyForRead() () from /usr/local/lib/libseasocks.so.1.3.2
#11 0xb6f80424 in seasocks::Server::handleConnectionEvents(seasocks::Connection*, unsigned int) () from /usr/local/lib/libseasocks.so.1.3.2
#12 0xb6f80960 in seasocks::Server::checkAndDispatchEpoll(int) () from /usr/local/lib/libseasocks.so.1.3.2
#13 0xb6f80f2a in seasocks::Server::loop() () from /usr/local/lib/libseasocks.so.1.3.2
#14 0xb6f80e72 in seasocks::Server::serve(char const*, int) () from /usr/local/lib/libseasocks.so.1.3.2
#15 0x0001c430 in std::function<void ()>::operator()() const (this=<optimized out>) at /usr/bin/../lib/gcc/arm-linux-gnueabihf/6.3.0/../../../../include/c++/6.3.0/functional:2127
#16 AuxTaskNonRT::empty_loop (this=<optimized out>) at core/AuxTaskNonRT.cpp:147
#17 AuxTaskNonRT::thread_func (ptr=<optimized out>) at core/AuxTaskNonRT.cpp:185
#18 0xb6ea159a in cobalt_thread_trampoline () from /usr/xenomai/lib/libcobalt.so.2
#19 0xb6e645e8 in start_thread () from /lib/arm-linux-gnueabihf/libpthread.so.0
```

This was a frontend that had been running for hours, and at some point it must have started sending `\u0000ampleRate":44100,"\u0000umChannels"`, which eventually crashed the scope server. Not sure what is happening on the client side, but the server shouldn't crash for malformed data.

**Comment by giuliomoro** [comment]
got the same stuff but now also fixed it 

```
{"numChannels":6,"sampleRate":46875,"numSliders":0,"frameWidth":1280,"plotMode":0,"triggerMode":0,"triggerChannel":0,"triggerDir":0,"triggerLevel":0,"xOffset":0,"upSampling":6,"downSampling":1,"FFTLength":1024,"FFTXAxis":0,"FFTYAxis":0,"holdOff":0,"interpolation":0,"xTimeBase":3,"sa\u0000pleRate":0.408158302307129,"frameHeight":721,"event":"connection-reply"}
```
